language: csharp
solution: Tetris.Engine.sln
install:
  - nuget restore Tetris.Engine.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Tetris.Engine.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tetris.Engine.Test/bin/Release/Tetris.Engine.Test.dll